#!/bin/bash
source /infra/utils

set -e
set -u
set -x

TARGET=${TARGET:-..}
PLUGIN=${PLUGIN:-}

cd $TARGET
cd $(setup_dir)
python setup.py sdist
pip install -U omero-py
pip install -U dist/*.tar.gz
python setup.py clean
rm -rf dist *egg-info src/*egg-info
